#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.7
  vars_files:
    - ../vars/docker.yml
#- name: os specific vars
#  include_vars: "{{ 'ansible_distribution'-'ansible_distribution_major_version' | lower }}"


  tasks:

    - name: print it out
      debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_distribution_major_version }}"  ## <-- dummy stuff ends
    - name: print facts
      debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_distribution_major_version }}"
    - name: os specific tasks
      include: "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml"

    - name: Alias fig to command docker compose
      lineinfile:
        path=/root/.bashrc
        line="alias fig='docker-compose'"
        owner=root
        regexp='^alias docker-compose'
        state=present
        insertafter=EOF
        create=True

    - name: Source .bashrc
      shell: "source /root/.bashrc"
      args:
        executable: /bin/bash

#    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
#      include_vars: "{{ item }}"
#      with_first_found:
#        - "{{ ansible_distribution }}.yml"
#        - "{{ ansible_os_family }}.yml"
#        - "default.yml"
