FROM docker.my4030.ir/ubuntu:bionic

ARG JAVA_VERSION
ARG PROXY

RUN echo 'Acquire::http::Proxy "${PROXY}";' > /etc/apt/apt.conf.d/01proxy

RUN set -ex \
    && export http_proxy=${PROXY} && export https_proxy=${PROXY} && \
    export HTTP_PROXY=${PROXY} && export HTTPS_PROXY=${PROXY} && \
    apt-get -y update && apt -y upgrade 

RUN set -ex \
    && export http_proxy=${PROXY} && export https_proxy=${PROXY} && \
    export HTTP_PROXY=${PROXY} && export HTTPS_PROXY=${PROXY} && \
    apt install -y software-properties-common

RUN set -ex \
#   && add-apt-repository -y ppa:linuxuprising/java \
    && add-apt-repository -y ppa:webupd8team/java && \
    apt-get update

RUN set -ex \
    && export http_proxy=${PROXY} && export https_proxy=${PROXY} && \
    export HTTP_PROXY=${PROXY} && export HTTPS_PROXY=${PROXY} && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-2 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java${JAVA_VERSION}-installer && \
    apt install -y oracle-java${JAVA_VERSION}-set-default && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ /tmp/* /var/tmp/*

ENV JAVA_HOME /usr/lib/jvm/java-${JAVA_VERSION}-oracle

CMD "/bin/bash"
